version: "3"
services:
  openapi-ui:
    image: swaggerapi/swagger-ui:v4.5.0
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml
    volumes:
      - ./openapi:/openapi
  db:
    platform: linux/x86_64
    image: mysql:8.0.28
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    command: --authentication_policy=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ryouomoi-checker
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ryouomoi-checker-db
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ryouomoi-checker-server
    env_file:
      - .env.compose
    depends_on:
      - db
  chat-server:
    build:
      context: ./chat
      dockerfile: Dockerfile
    container_name: ryouomoi-checker-chat-server
    env_file:
      - .env.compose
    ports:
      - "3001:3001"
    depends_on:
      - db
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - chat-server
volumes:
  db-data:
    driver: local
