version: "3"
services:
  openapi-ui:
    image: swaggerapi/swagger-ui:v4.5.0
    container_name: "ryouomoi-checker-openapi-ui"
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml
    volumes:
      - ./openapi:/openapi
