name: Deploy OpenAPI

on:
  push:
    branches: [ master ]

jobs:
  deploy_openapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        uses: actions/upload-artifact@v2
        with:
          path: openapi
